package leetcode;

/**
 * Created by Hua on 8/28/16.
 *
 *  Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.

 */
public class N389_FindtheDifference {
    // Google
    // 7ms, hashmap o(n)
    public char findTheDifference(String s, String t) {
        int[] map = new int[128];
        for(char c: s.toCharArray()) map[c]++;
        for(char c: t.toCharArray()){
            if(--map[c] < 0) return c;
        }
        return 0;
    }


}

